language: minimal

services:
  - docker

stages:
  - build

env:
  global:
    IMAGE_TAG=$TRAVIS_TAG

jobs:
  include:
    - name: Pull Request
      if: type = pull_request
      stage: build
      script: make build
    - name: Staging
      if: branch = master AND NOT (type = pull_request)
      stage: build
      script: make build
    - name: Release
      if: tag IS present
      stage: build
      script: make release
